version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: "gradle"
    directory: "/"

    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"

    schedule:
      interval: "weekly"
